openapi: "3.0.1"
info:
  title: news api
  contact:
    name: API Support
    email: dmitrym.dev@websm.io
  version: 1.0.0

paths:
  /:
    get:
      summary: get list of news
      parameters:
        - name: offset
          in: query
          schema:
            type: integer
          description: first news item number
        - name: limit
          in: query
          schema:
            type: integer
          description: limit news items number
        - name: order
          in: query
          schema:
            type: object
            additionalProperties:
              type: string
          style: deepObject
          explode: true
          example:
            creationDate: desc
      responses:
        '200':
          description: list of news
          content:
            application/hal+json:
              schema:
                type: any
        '404':
          description: index page not found
          content:
            application/hal+json:
              schema:
                properties:
                  errors:
                    items:
                      properties:
                        message:
                          type: string
        '500':
          description: server error
          content:
            application/hal+json:
              schema:
                properties:
                  errors:
                    items:
                      properties:
                        message:
                          type: string


